language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "0.13"
before_install:
  - npm install -g npm
before_script:
  - npm install grunt-cli -g
  - npm uninstall grunt # https://github.com/npm/npm/issues/3958
  
